### ISSUE TITLE
gnu-efi 3.0.16+ breaks sbsigntools (sbvarsign)

### ISSUE THREAD

**Issue by rathann** [ncroxon/gnu-efi#52]
(originally reported downstream in Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=2310759)

mkosi uses sbvarsign to sign PK, KEK and db signature lists for use with systemd-boot secure boot auto-enrollment. sbsigntools, when built against gnu-efi 3.0.16+ produces a signed PK signature list that results in a security violation when systemd-boot tries to enroll it within a UEFI OVMF virtual machine. With sbsigntools-0.9.5-1.fc38.x86_64.rpm from Fedora 38 the signed PK signature list is accepted again by the OVMF secure boot firmware.

This was bisected by the reporter to commit 189200d0b0f6fff473d302880d9569f45d4d8c4d .

**Steps to Reproduce:**
On a Fedora 40 or rawhide system, run the following:
```
git clone https://github.com/systemd/mkosi
ln -s $PWD/mkosi/bin/mkosi /usr/local/bin/mkosi
mkdir tmp
cd tmp
mkosi genkey
mkosi -d fedora -r rawhide -p kernel-core -p systemd -p udev -p systemd-boot --secure-boot --secure-boot-auto-enroll=yes -i -f qemu
```

**Actual Results:**
```
Enrolling secure boot keys from directory: \loader\keys\auto
Failed to write PK secure boot variable: Security violation
```

**Expected Results:**
```
Enrolling secure boot keys from directory: \loader\keys\auto
Custom Secure Boot keys successfully enrolled, rebooting the system now!
```

**Comment by rathann** [comment]
@gmbr3 could you take a look?

**Comment by pbatard** [comment]
For what is worth, EDK2 explicitly defines `CHAR16` as `unsigned short` ([[1](https://github.com/tianocore/edk2/blob/0f3867fa6ef0553e26c42f7d71ff6bdb98429742/MdePkg/Include/X64/ProcessorBind.h#L136)]. [[2](https://github.com/tianocore/edk2/blob/0f3867fa6ef0553e26c42f7d71ff6bdb98429742/MdePkg/Include/AArch64/ProcessorBind.h#L82)]), whereas defining it as `wchar_t` [leaves its signedness very much undefined](https://stackoverflow.com/a/11953419/1069307).

I think we probably want to go back to defining `CHAR16` as `unsigned short`.

**Comment by gmbr3** [comment]
> For what is worth, EDK2 explicitly defines `CHAR16` as `unsigned short` ([[1](https://github.com/tianocore/edk2/blob/0f3867fa6ef0553e26c42f7d71ff6bdb98429742/MdePkg/Include/X64/ProcessorBind.h#L136)]. [[2]
(https://github.com/tianocore/edk2/blob/0f3867fa6ef0553e26c42f7d71ff6bdb98429742/MdePkg/Include/AArch64/ProcessorBind.h#L82)]), whereas defining it as `wchar_t` [leaves its signedness very much undefined](https://stackoverflow.com/a/11953419/1069307).

`unsigned short` triggers warnings in C++ if you store a character in it
`wchar_t` doesn't just have 'undefined' signedness - it's effectively undefined undefinedness (that's just C standard not being precise) - GCC aliases it to `unsigned short` under `-fshort-wchar` in C but is a distinct type in C++ which prevents the above issue

> 
> I think we probably want to go back to defining `CHAR16` as `unsigned short`.

I literally mostly fixed this already (by not doing this due to the above) as shown in the bug report that was tagged above [here](https://bugzilla.redhat.com/show_bug.cgi?id=2310759#c4)

sbsigntools didn't read the build instructions README (although this wasn't clear where to find until recently) [here](https://bugzilla.redhat.com/show_bug.cgi?id=2310759#c2)

Done in
ncroxon/gnu-efi@edfda7c396134c7109444b230ce4b0da1e61d524
ncroxon/gnu-efi@f8ebcfc077665013aba6f26f98404e246093bdd6

`uint16_t` isn't perfect either but it's the closest IMHO

**Comment by rathann** [comment]
Thanks. I'll fix this in sbsigntools, then.

**Comment by pbatard** [comment]
> `unsigned short` triggers warnings in C++ if you store a character in it

Then I'm going to assert that it's your job to silence that warning downstream, rather than make the upstream toolchain, whose mandate should be to be as close to the EDK2 API, **explicitly deviate** from the EDK2 API.

As far as I am concerned, gnu-efi is AMD to EDK2's Intel. If EDK2 has quirks, then we follow these quirks to the letter, to ensure as close a compatibility as we can. Even if these quirks have negative consequences and we see ways to fix them.

So, if EDK2 says that `CHAR16` is `unsigned short` then `CHAR16` **is** `unsigned short`.

Otherwise, it makes no sense for us to go through changes like a093fe03786b15ecabaa0d16f84c8133f76ca0c0 or f3656c88007a775562b625a2cfe1bc54c1170bfe or f719f7d83897100eb7443498ea17f5fe5cd7fa51 while also explicitly deviating for ABI/API stuff we don't like from EDK2.

You and I clashed about this in the past, so I'm going to have to reiterate that we want to be careful not to see gnu-efi as something we can shape accordingly to the specific needs of our downstream projects (such as getting an annoying warnings there, and deciding we can simply fix them in gnu-efi by explicitly deviating from the EDK2 API), but instead as a toolchain that is relied on by others, and that needs to maintained as as close as possible a drop-in replacement for EDK2.

If not, then we need to make it very explicit, on the project page and README, that gnu-efi is not designed to be compatible with EDK2, and that we have purposefully introduced changes that we know will break EDK2 compatible code.

This being said, I can 100% understand where you are coming from, and, had this issue not been opened, I would never have seen a simple switch from `unsigned short` to `wchar_t` as that big a deal.

Still, in direct consideration of this issue, I don't think deviating from the EDK2 API because we know it will fix warnings in downstream projects is the right approach, and I think we need to make a decision here on whether we want this project to be AMD to EDK2's Intel, **with all the quirky, annoying compatibility it requires** or something else...

**Comment by ncroxon** [comment]
> > `unsigned short` triggers warnings in C++ if you store a character in it
> 
> Then I'm going to assert that it's your job to silence that warning downstream, rather than make the upstream toolchain, whose mandate should be to be as close to the EDK2 API as possible, **explicitly deviate** from the EDK2 API.
> 
> As far as I am concerned, gnu-efi is AMD to EDK2's Intel. If EDK2 has quirks, then we follow these quirks to the letter, to ensure as close a compatibility as we can. Even if these quirks have negative consequences and we see ways to fix them.
> 
> So, if EDK2 says that `CHAR16` is `unsigned short` then `CHAR16` **is** `unsigned short`.
> 
> Otherwise, it makes no sense for us to go through changes like [a093fe0](https://github.com/ncroxon/gnu-efi/commit/a093fe03786b15ecabaa0d16f84c8133f76ca0c0) or [f3656c8](https://github.com/ncroxon/gnu-efi/commit/f3656c88007a775562b625a2cfe1bc54c1170bfe) or [f719f7d](https://github.com/ncroxon/gnu-efi/commit/f719f7d83897100eb7443498ea17f5fe5cd7fa51) while also explicitly deviating for ABI/API stuff we don't like from EDK2.
> 
> You and I clashed about this in the past, so I'm going to have to reiterate that we want to be careful not to see gnu-efi as something we can shape accordingly to the specific needs of our downstream projects (such as getting annoying warnings there, and deciding we can simply fix them in gnu-efi by explicitly deviating from the EDK2 API), but instead as a toolchain that is relied on by others, and that needs to maintained as as close as possible a drop-in replacement for EDK2.
> 
> If not, then we need to make it very explicit, on the project page and README, that gnu-efi is not designed to be compatible with EDK2, and that we have purposefully introduced changes that we know will break EDK2 compatible code.
> 
> This being said, I can 100% understand where you are coming from, and, had this issue not been opened, I would never have seen a simple switch from `unsigned short` to `wchar_t` as that big a deal.
> 
> Still, in direct consideration of this issue, I don't think deviating from the EDK2 API because we know it will fix warnings in downstream projects is the right approach, and I think we need to make a decision here on whether we want this project to be AMD to EDK2's Intel, **with all the quirky, annoying compatibility it requires** or something else...

**Comment by ncroxon** [comment]
I agree with Pete here on the direction of gnu-efi.

**Comment by gmbr3** [comment]
> Then I'm going to assert that it's your job to silence that warning downstream, rather than make the upstream toolchain, whose mandate should be to be as close to the EDK2 API as possible, **explicitly deviate** from the EDK2 API.

Deviation != compatibility problem

> 
> As far as I am concerned, gnu-efi is AMD to EDK2's Intel. If EDK2 has quirks, then we follow these quirks to the letter, to ensure as close a compatibility as we can. Even if these quirks have negative consequences and we see ways to fix them.

WHY oh why - there is literally no problem - fuss over nothing
Also there is subtle differences between AMD64 and Intel 64 but that's beside the point

> 
> You and I clashed about this in the past, so I'm going to have to reiterate that we want to be careful not to see gnu-efi as something we can shape accordingly to the specific needs of our downstream projects

I've literally sorted stuff other people wanted fixing as well - this isn't purely for me
(I am an unpaid developer of a Linux distribution - I could just ignore problems including the problems with the project to start with)
I'm not associated with any downstream of this officially - I fix problems to help other people

> 
> Still, in direct consideration of this issue, I don't think deviating from the EDK2 API because we know it will fix warnings in downstream projects is the right approach, and I think we need to make a decision here on whether we want this project to be AMD to EDK2's Intel, **with all the quirky, annoying compatibility it requires** or something else...

I personally can't wait for a UEFI `CHAR32` type to be created and everything to sh** the bed very quickly because no-one is thinking forwards compatibility by the looks of it

Abuse of types != Quirky, annoying
Living in C standard 1999 (I wasn't even born) != Quirky, annoying
Forcing badly designed options on GCC != Quirky, annoying

`unsigned short` is logically the same (apart from specific platform semantics) as `uint16_t` (changing that just puts us back in 1999)

EDK2 uses `L""` string literals which are type (of guess what) `wchar_t` no matter what you tell GCC to do
If you tell GCC to `-fshort-wchar` it aliases `wchar_t` to `unsigned short` instead of `char32_t`
This means it works but badly - after all L means long as in 32 bit type
And if you use it with the `uint16_t` it still works because the types are compatible and logically the same

I've literally introduced changes to bring functions closer to EDK2 as you pointed out - if you think I'm not watching compatibility that'd be wrong - even if at the cost of compatibility with gnu-efi < 4.0

And it's almost like I predicted [this](https://github.com/ncroxon/gnu-efi?tab=readme-ov-file#4-convenient-and-portable-generation-of-unicode-string-literals)

**Comment by gmbr3** [comment]
sbsigntools doesn't set `-fshort-wchar` - **THEY ARE THE PROBLEM HERE**
Literally not following anyone's rules **EDK2 or gnu-efi**

**Comment by pbatard** [comment]
The fact that sbsigntools should set `-fshort-wchar` (which they should) doesn't invalidate the point that if we define a primary type one way, and EDK2 defines it a different way, people who use gnu-efi are bound to encounter assignment incompatibility issues compared to EDK2.

If I know that EDK2 defines `CHAR16` as `unsigned short` and I create a project, I expect to be able to use logic that relies on the fact that `CHAR16` is an unsigned short (such as using logic that works on `unsigned shorts` for `CHAR16` variables).

The minute you define it to something that may or may not be compatible with `unsigned short`, and that only becomes compatible with it through a compiler flag, then no matter how much you push for that flag to be seen as "mandatory" in the toolchain, you are asking for trouble (because you will find that, for one reason or another, people will encounter the need to negate the previous flags, which compilers usually happily allow, and which is something I have done quite a few times with EDK2 flags).

All someone has to do is add `-fno-short-char` to their project, for one reason or another (and it is not up to us to judge that reason), for them to potentially run into a lengthy troubleshooting session between EDK2 and gnu-efi produced code to in order to determine that the use of a different primitive and the negation of `-fshort-wchar` is their underlying issue.

**Comment by gmbr3** [comment]
Literally a statement of my point and why it's currently set to `uint16_t`
CHAR16 **isn't** `wchar_t` right now
The string literals are set to 'u' (aka `uint16_t`) unlike the 'L' that EDK2 uses - this was the **IMPORTANT** part as it fixes the `-fno-short-wchar` issue
`uint16_t` is **100%** logically compatible with `unsigned short`
**Nothing to change unless you really like C99**

**Comment by gmbr3** [comment]
> I must admit I completely missed that, despite the fact that you explicitly pointed to the commit, so my apologies for indeed raising a fuss over a matter that did not exist.

Seriously don't worry 😃

> 
> If we do have `uint16_t` then I am obviously dropping my objection (and I do not quite get why OP ran into their issue, unless they are compiling with a gnu-efi version that does not include [edfda7c](https://github.com/ncroxon/gnu-efi/commit/edfda7c396134c7109444b230ce4b0da1e61d524)).

Cough.. cough
Once again I say
**It's time for gnu-efi [4.0](https://github.com/ncroxon/gnu-efi/issues/51#issuecomment-2462635117)**

**Comment by rathann** [comment]
> If we do have `uint16_t` then I am obviously dropping my objection (and I do not quite get why OP ran into their issue, unless they are compiling with a gnu-efi version that does not include [edfda7c](https://github.com/ncroxon/gnu-efi/commit/edfda7c396134c7109444b230ce4b0da1e61d524)).

We are. That commit hasn't made it into a release just yet.
